# Use root/example as user/password credentials
version: '3.1'

services:

      
  Virtual-white-board-database:
    container_name: 'White-board-Database'
    image: mariadb:latest
    hostname: whiteboardDatabase
    restart: always
    ports:
      - 3320:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: whiteboardDatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin